runtime: python37

instance_class: F4_1G

handlers:

#- url: /static  
#  static_dir: static

- url: /.*  
  script: auto

resources:
  memory_gb: 4  

#libraries:  
#- name: ssl    
#  version: latest